name: vivah_ai
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.5
  permission_handler: ^11.0.1
  speech_to_text: ^6.5.1
  fluttercontactpicker: ^4.7.0
  video_player: ^2.7.2
  camera: ^0.10.5+7
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  firebase_auth_platform_interface: ^7.0.9
  firebase_auth_web: ^5.8.13
  firebase_core_web: ^2.10.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.0
  screenshot: ^2.1.0
  share: ^2.0.4
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  story_view: ^0.16.0
  image_gallery_saver: ^2.0.3
  chewie: ^1.7.4
  photo_view: ^0.14.0
  read_pdf_text: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/apple.png
    - assets/google.png
    - assets/pic.png
    - assets/invite.jpg
    - assets/vivah.jpg
    - .env