// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCruj4Nc_w_S46mfrEYJ14zfIHGVTyeVRU',
    appId: '1:780447259674:web:6d37691f317232c4eb45a3',
    messagingSenderId: '780447259674',
    projectId: 'vivah-ai',
    authDomain: 'vivah-ai.firebaseapp.com',
    storageBucket: 'vivah-ai.appspot.com',
    measurementId: 'G-Z4HXZC92HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdspSu14X5-WssU1dCMH4uGe-XiQhJUk',
    appId: '1:780447259674:android:b326d51812c3efa7eb45a3',
    messagingSenderId: '780447259674',
    projectId: 'vivah-ai',
    storageBucket: 'vivah-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdpaR86HDmVRkUnChiPEEPrwteeMNN4g8',
    appId: '1:780447259674:ios:faa63f0b2cd95664eb45a3',
    messagingSenderId: '780447259674',
    projectId: 'vivah-ai',
    storageBucket: 'vivah-ai.appspot.com',
    androidClientId: '780447259674-v788g13d35q9dcka7or22fm79c6nim0h.apps.googleusercontent.com',
    iosClientId: '780447259674-3ji405i5ddv5vamckoqadejom7bn48uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivahAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdpaR86HDmVRkUnChiPEEPrwteeMNN4g8',
    appId: '1:780447259674:ios:01e684548394296beb45a3',
    messagingSenderId: '780447259674',
    projectId: 'vivah-ai',
    storageBucket: 'vivah-ai.appspot.com',
    androidClientId: '780447259674-v788g13d35q9dcka7or22fm79c6nim0h.apps.googleusercontent.com',
    iosClientId: '780447259674-d3q9dsc9hsq4q96f25om6mpifv0ognfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivahAi.RunnerTests',
  );
}
